// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlzhacpuqnepdwevojma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsemhhY3B1cW5lcGR3ZXZvam1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1OTE3MTksImV4cCI6MjA4OTE2NzcxOX0.gLS4WGEPzrr8alJBGuNaRTqshtjJ-UhU1apfsmd5LsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});